### PR TITLE
rust-1.0.0_beta.ebuild

### PR DESCRIPTION
**Pull request by geovex**

### CODE REVIEW

**Comment by Heather** [comment]
@geovex thank you

**Comment by Heather** [comment]
@geovex please clean up Manifest file:

```
+DIST rust-stage0-2015-03-27-5520801-linux-i386-1ef82402ed16f5a6d2f87a9a62eaa83170e249ec.tar.bz2 18104375 SHA256 f948477a43dc14436b218a24a81097d0460ca2e2177bebabba24fae89fc62b4b SHA512 86b28b03e8ef730620e593d00786b14736e05fdf5f312ab194175340fad1f24e169f69e381e73c1eb102f059f47a926dabd93bfaad46c50caa3717ee10412a5c WHIRLPOOL 086875d15228ebc68334eb4d663207917e1876044e12296426a00a0fec88a1325fe6a5e620e51b58eb08a58c27896df5fbb6d6ca992e0d754a98697f1bc9ed17
+DIST rust-stage0-2015-03-27-5520801-linux-x86_64-ef2154372e97a3cb687897d027fd51c8f2c5f349.tar.bz2 17935368 SHA256 b62eed6bdb3cb356c90d587e9d9ee7fb5aedad917ff872c04e67e20b4c8f1c91 SHA512 0a978be4865f9e77c5ab552d423e21f1edefc767bc8a8d2936b45b0a9194648c5fb3c32cec0eaea438ad1339802faa1504b511956c2d71f73f2eb0439a4d7b99 WHIRLPOOL 89b0b8c51fd072c33afe8e98bc9aaea301ffa810a166b612d10dd89bbc491c3350f591f57bc3494066d71402910519b07cffa95d2802bdd6334aaad0c2f79334
```

**Comment by Heather** [comment]
@geovex strange, ah good so beta is tarballs from `2015-03-27` nightlies?

**Comment by geovex** [comment]
it uses stage0 from this nightlies

**Comment by Heather** [comment]
@geovex thanks, understood.

**Pull request merged**
