### PR TITLE
Add ebuilds for rust-1.0.0-beta.3 (second try)

### PR DESCRIPTION
**Pull request by gentoo90**

### CODE REVIEW

**Comment by jauhien** [comment]
@gentoo90: you have not fixed an issue. I see no difference with the previous try. Or am I wrong?

**Comment by jauhien** [comment]
@gentoo90: could you, please, always use the latest version of this repo as a base for your pull requests?

What you need to do now -- update to the latest version and use ebuilds from it as a base for the pull request.

Please, through away previous commits and make `push -f` to push your  changes, so there is only one correct commit in this pull request.

**Comment by gentoo90** [comment]
Done. Sorry for my lack of attention.

**Comment by jauhien** [comment]
@gentoo90: thanks

**Pull request merged**
