### PR TITLE
Migration to app-eselect category

### PR DESCRIPTION
**Pull request by Nexion**
Lately all eselect-* packages were moved to new app-eselect category. Package app-eselect/eselect-rust already exists in the official tree, thus dependencies in this overlay lead to conflict.

### CODE REVIEW

**Comment by Heather** [comment]
THANK YOU!

**Comment by Nexion** [comment]
You're welcome :)

**Comment by JelteF** [comment]
This change breaks my world file, since app-eselect/eselect is depended on although it doesn't exist. Travis says so as well.

**Comment by Heather** [comment]
@JelteF true...

**Comment by Heather** [comment]
@JelteF try now

**Comment by JelteF** [comment]
My issue has been fixed, but Travis still complains about another issue. The added C, which seems to be added by accident.

**Comment by Nexion** [comment]
@JelteF just removed the typo, sorry for that.

**Comment by Heather** [comment]
... yes my review was also terrible there
@JelteF thank you for catching this that early

**Comment by JelteF** [comment]
No problem, thanks for maintaining the repo

**Pull request merged**
