### PR TITLE
Rust 1.0.0_alpha

### LINKED ISSUE #50: Rust 1.0.0 alpha is out

### PR DESCRIPTION
**Pull request by geovex**
rust 1.0.0_alpha ebuild.
resolves #50

### CODE REVIEW

**Comment by Heather** [comment]
@geovex repoman says:
```
dependency.bad                40
dev-lang/rust/rust-1.0.0_alpha.ebuild: DEPEND: ~amd64(default/linux/amd64/13.0) ['>=sys-devel/llvm-3.6.0[multitarget(-)]']
```

**Comment by geovex** [comment]
@Heather I'm working on it. Sorry for failed tests.

**Comment by geovex** [comment]
I had to remove `system-llvm` USEflag. Will return as soon as llvm-3.6 will be in portage.

**Comment by Heather** [comment]
@geovex sad... but okay

**Comment by jauhien** [comment]
You can mask this USE in alpha and make it for this case depend on the live llvm. This is the right way for solving this problem.

**Comment by geovex** [comment]
thanks for the tip @jauhien.
@Heather may pull geov/gentoo-rust@da3d2835ef806ba76631907dacf125116128110b from my rust_1.0 branch. Or should I create another pull request.

**Pull request merged**
