### PR TITLE
new path for nightly sources

### PR DESCRIPTION
**Pull request by geovex**
Now nightly sources link ends with *src.tar.gz. This requires changes in
ebuild.

### CODE REVIEW

**Comment by o01eg** [comment]
Did not you get error: `mv: cannot stat ‘/tmp/portage/dev-lang/rust-999-r1/image//usr/bin/rust-lldb’: No such file or directory` ?

**Comment by o01eg** [comment]
Also I got into file collisions with =rust-9999-r3:
```
 * Searching all installed packages for file collisions...
 * 
 * Press Ctrl-C to Stop
 * 
 * dev-lang/rust-9999-r3:git::rust
 * 	/usr/share/doc/rust/COPYRIGHT.bz2
 * 	/usr/share/doc/rust/LICENSE-APACHE.bz2
 * 	/usr/share/doc/rust/LICENSE-MIT.bz2
 * 	/usr/share/doc/rust/README.md.bz2
```

**Comment by geovex** [comment]
@o01eg was right, I requested wrong branch. Besides there are at least problems with slots so i try to close request.

**Comment by Heather** [comment]
@o01eg thanks for review :)

**Pull request closed without merging**
