### PR TITLE
Update rust and rust-bin to 1.1.0

### PR DESCRIPTION
**Pull request by funkill**
With llvm version 3.6.1 compilation of rust 1.1.0 fails with error `error: linking with `cc` failed: exit code: 1`. If compile with rust's llvm, all ok

### CODE REVIEW

**Comment by jauhien** [comment]
Keyworded ebuild cannot depend on not keyworded one (I mean, llvm 9999). What version of LLVM rust 1.1.o needs? If you are sure that 9999, we need to mask appropriate USE.

**Comment by gentoo90** [comment]
Shouldn't `1.0` and `1.1` be in different slots like versions of `gcc`?

**Comment by jauhien** [comment]
@gentoo90: no, they should be in the same 'stable' slot. There is no reason to have them simultaneously (like e.g. gcc 4.7.1 and 4.7.2).

**Comment by vberger** [comment]
Is the llvm-9999 dependency really necessary ?
Yesterday again I compiled rust master against my system llvm-3.6.1 without any issue, and I would find it very surprising that rust stable require a more recent llvm version than rust-9999...

**Comment by vberger** [comment]
On my `x64_64` system:
I have llvm-3.6.1 with useflags `libffi multitarget ncurses static-analyzer xml -clang -debug -doc -gold -libedit -ocaml -python -test`.

I compiled rust-1.1.0 with useflags `system-llvm -clang -debug -doc -libcxx` (the ebuild from this PR with the llvm dependency reverted to `>=3.6.0`).

Everything went fine.

**Comment by jauhien** [comment]
Well, let me see, I will test it today and look what's going on with LLVM and rust. Please, do not merge this PR so far.

**Comment by Heather** [comment]
@jauhien sure, to keep this contribution you can pull it to your fork and then commit on top of it and re-create it as new PR :+1:

**Comment by jauhien** [comment]
See PR #137.

**Pull request closed without merging**
